name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Angular Deploy gh-pages Actions
      # You may pin to the exact commit or the version.
      # uses: AhsanAyaz/angular-deploy-gh-pages-actions@26ffbdb76b46ce3d649d046f1f7f45099654cfd7
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
      with:
        # Github access token token used to deploy on gh_pages. You can find it on Github.
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        # base href for the app
        base_href: https://devexpress.github.io/web-dashboard-demo-preview/
        angular_dist_build_folder: dist/web-dashboard-demo-preview
        # branch on which the angular build will be deployed
        deploy_branch: site
